syntax on
filetype plugin on

""" Options """
set fenc=utf-8
set hidden
set autoread
set showcmd
set signcolumn=yes
" Indentation
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set smarttab
set list
set listchars=tab:>-,trail:-,extends:>,precedes:<,nbsp:%
" Views
set title
set number
set relativenumber
set cursorline
set showmatch
set laststatus=2
set statusline=%F%m\ %<[%{&fenc!=''?&fenc:&enc}]\ [%Y]\ [ln:%l,col:%v]
set showtabline=2
" Controls
set mouse=a
set whichwrap=b,s,h,l,<,>,[,],~
" Search
set hlsearch
set incsearch
set smartcase
set ignorecase
" Split
set splitbelow
set splitright
" Backspace
set backspace=indent,eol,start
" Menu
set wildmenu
set wildmode=longest:full,full

" .viminfo
set viminfo+=n~/.local/share/vim/viminfo

""" Keymaps """
nnoremap ;      :
nnoremap <silent>j      gj
nnoremap <silent>k      gk
nnoremap <silent><Down> gj
nnoremap <silent><Up>   gk
nnoremap <silent><C-a>  ^
nnoremap <silent><C-e>  $
inoremap <silent> jj <ESC>
vnoremap <silent><C-a>  ^
vnoremap <silent><C-e>  $

""" terminal """
command! -nargs=* T botright term <args>

""" Colorscheme """
colorscheme desert
