name: ubuntu

on:
  push:
    branches:
      - main

jobs:
  macOS:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: curl -sL https://raw.githubusercontent.com/ShuN6211/dotfiles/refs/heads/main/install.sh | sh
